# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KpengIjkPlayer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AFNetworking', '~> 3.2.1'
  # Pods for KpengIjkPlayer
  pod 'ijkplayer', '~> 1.1.3'
#  pod 'FMDB'
  pod 'CocoaHTTPServer', '~> 2.3'
end
